# Generated by Django 5.2 on 2025-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Ссылка на источник')),
                ('source', models.CharField(choices=[('Habr', 'Habr'), ('Vc', 'Vc')], help_text='Источник')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0, help_text='Положительный голос')),
                ('downvotes', models.IntegerField(default=0, help_text='Отрицательный голос')),
            ],
        ),
    ]
