# Generated by Django 5.2 on 2025-04-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator_app', '0002_alter_article_options_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('unique_visitors', models.JSONField(default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='aggregator_app.article')),
            ],
        ),
    ]
