# Generated by Django 5.2 on 2025-05-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator_app', '0004_alter_articlestats_unique_visitors_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
